services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - ML_SERVICE_URL=http://ml:4242
    restart: unless-stopped

  ml:
    build:
      context: ./machine_learning
    ports:
      - "4242:4242"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
